name: 'Test failing steps'
on:
  workflow_dispatch:

jobs:
  stale:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          exit 1
      - name: Step 2
        run: |
          exit 0
