name: 'Test failing steps'
on:
  workflow_dispatch:

jobs:
  stale:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "Step 1"
          exit 1
      - name: Step 2
        run: |
          echo "Step 2"
          exit 0
